// <auto-generated />
namespace HBSIS.TCC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DBsete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBsete));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281809074_DBsete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
